---
title: "Aplicação do TCL"
output:
  pdf_document:
    toc: yes
    toc_depth: '3'
  html_document:
    toc: yes
    toc_depth: 3
    toc_float:
      collapsed: no
      smooth_scroll: yes
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```



### Criação dos dados

```{r, include=FALSE}
library(tidyverse)
library(lmtest)
library(broom)
library(car)

n <- 10 ^ 7
x1 <- rnorm(n, 100, 5)
resposta <- 25 + 3*x1 + rpois(n, 5)
dados <- tibble(resposta,x1)
```




```{r}
armazenados <- c()
for (quant in c(10,100,1000,10000)){
  for (c in 1:1000){
  dados_amostrados <- dados %>% sample_n(quant)
  modelo <- lm(resposta ~ ., data = dados_amostrados)
  armazenados <- rbind(armazenados, tidy(modelo) %>% select(term, estimate) %>% mutate(quant_amostra = paste(quant, " amostras", sep = " ")))
}
}


```


### Mostrando histograma das estimativas


```{r}
armazenados <- armazenados %>% filter(term != "(Intercept)")
ggplot(armazenados, aes(estimate, fill = quant_amostra)) + geom_density() + theme_minimal() + facet_wrap(vars(quant_amostra), scale = "free")
```


### Mostrando um boxplot


```{r}
armazenados <- armazenados %>% filter(term != "(Intercept)")
ggplot(armazenados, aes(estimate, fill = quant_amostra)) + geom_boxplot() + theme_minimal() 
```